--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ClickedTran/BossBarAPI
build-by-default: true
branches:
- Master
projects:
  BossBarAPI:
    path: ""
    model: virion
    type: library
...
